name: ci

on:
  push:
    branches:
      - fe-cc2
      - main
  pull_request:
    branches:
      - fe-cc2
      - main

jobs:
  ci:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Cache node_modules 
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: yarn

      - name: Run lint
        run: yarn lint

      # - name: Run tests
      #   run: yarn test

      # - name: Run e2e test
      #   run: yarn cypress:test

